# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Autodia
version:      2.00
version_from: Autodia.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    File::Find:                    0
    Getopt::Std:                   0
    GraphViz:                      0
    Inline:                        0
    Inline::Java:                  0
    SpringGraph:                   0.02
    Template:                      1
    VCG:                           0.4
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
